# Generated by Django 5.2.7 on 2025-10-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_producttype_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex'), ('niche', 'Niche'), ('kids', 'Kids')], max_length=50, unique=True),
        ),
    ]
