# Generated by Django 5.2.7 on 2025-10-26 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('featured', models.BooleanField(default=False, help_text='Mark as featured to show on the homepage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, help_text='Leave empty if this FAQ is for general business questions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
