# Generated by Django 5.0.10 on 2026-03-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_tag_alter_product_options_brand_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='scent_notes',
        ),
        migrations.AddField(
            model_name='product',
            name='base_notes',
            field=models.CharField(blank=True, help_text='e.g. Brown Sugar, Patchouli', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='heart_notes',
            field=models.CharField(blank=True, help_text='e.g. White Gardenia, Jasmine', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='top_notes',
            field=models.CharField(blank=True, help_text='e.g. Pear Blossom, Bergamot', max_length=255),
        ),
    ]
