# Generated by Django 5.0.10 on 2026-03-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_remove_product_scent_notes_product_base_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Summer Sale 2026', max_length=255)),
                ('method', models.CharField(choices=[('CODE', 'Code'), ('AUTO', 'Automatic')], default='CODE', max_length=20)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('discount_type', models.CharField(choices=[('PRODUCT_AMOUNT', 'Amount off products'), ('BUY_X_GET_Y', 'Buy X get Y'), ('ORDER_AMOUNT', 'Amount off order'), ('FREE_SHIPPING', 'Free shipping')], max_length=20)),
                ('min_requirement_type', models.CharField(choices=[('QTY', 'Minimum quantity'), ('AMOUNT', 'Minimum purchase')], default='QTY', max_length=20)),
                ('min_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('value_type', models.CharField(choices=[('PERCENT', 'Percentage'), ('FIXED', 'Fixed Amount'), ('FREE', 'Free')], default='PERCENT', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('once_per_customer', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requirement_products', models.ManyToManyField(blank=True, related_name='required_in_discounts', to='products.product')),
                ('reward_products', models.ManyToManyField(blank=True, related_name='rewarded_in_discounts', to='products.product')),
            ],
        ),
    ]
